version: "3.7"
services:
  zeppelin:
    image: zeppelin:0.8.1
    container_name: zeppelin
    hostname: zeppelin
    ports:
      - "8100:8080"
    volumes:
      - /tmp/zeppelin-data/notebook:/notebook
      - /tmp/spark-data:/opt/spark-data
    environment:
      - "ZEPPELIN_LOG_DIR=/logs"
      - "ZEPPELIN_NOTEBOOK_DIR=/notebook"